ARG tempo
ARG 2.10

FROM dhi.io/${IMAGE_NAME}:${IMAGE_TAG}

LABEL source.image="dhi.io/${IMAGE_NAME}:${IMAGE_TAG}" \
      source.registry="dhi.io" \
      source.tag="${IMAGE_TAG}" \
      source.name="${IMAGE_NAME}" \
      description="Hardened ${IMAGE_NAME} image from Docker Hardened Images"
